#pragma once

#define FCITXUTILS_EXPORT
#define FCITXUTILS_NO_EXPORT
#define FCITXUTILS_DEPRECATED __attribute__((deprecated))
#define FCITXUTILS_DEPRECATED_EXPORT FCITXUTILS_DEPRECATED
#define FCITXUTILS_DEPRECATED_NO_EXPORT FCITXUTILS_DEPRECATED
