#pragma once

#define FCITXCONFIG_EXPORT
#define FCITXCONFIG_NO_EXPORT
#define FCITXCONFIG_DEPRECATED __attribute__((deprecated))
#define FCITXCONFIG_DEPRECATED_EXPORT FCITXCONFIG_DEPRECATED
#define FCITXCONFIG_DEPRECATED_NO_EXPORT FCITXCONFIG_DEPRECATED
