#pragma once

#define FCITXCORE_EXPORT
#define FCITXCORE_NO_EXPORT
#define FCITXCORE_DEPRECATED __attribute__((deprecated))
#define FCITXCORE_DEPRECATED_EXPORT FCITXCORE_DEPRECATED
#define FCITXCORE_DEPRECATED_NO_EXPORT FCITXCORE_DEPRECATED
